export const PATH = {
  PLUS_LOGIN: "/pages/plus/login/index",
  HOME: "/pages/index/index/index",
  LOGIN: "/pages/app/login/index",
  NOT_FOUNT: "/pages/app/404/index",
  WEBVIEW: "/pages/app/webview/index",
  PLUS: "/pages/plus/index/index",
  PLUS_TIMETABLE: "/pages/plus/study/timetable/index",
  PLUS_CLASSROOM: "/pages/plus/study/classroom/index",
  PLUS_GRADE: "/pages/plus/study/grade/index",
  PLUS_EXAM: "/pages/plus/study/exam/index",
  PLUS_PLAN: "/pages/plus/information/plan/index",
  PLUS_SITUATION: "/pages/plus/information/situation/index",
  PLUS_BOOK: "/pages/plus/information/book/index",
  USER: "/pages/user/index/index",
  POST: "/pages/user/post/index",
  ABOUT: "/pages/user/about/index",
  REWARD: "/pages/user/reward/index",
};
